# Generated by Django 4.2 on 2023-05-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payemnt_id',
            new_name='payment_id',
        ),
    ]
